### ISSUE TITLE
onChange is not working

### ISSUE THREAD

**Issue by stonexer** [react-component/tree-select#124]
value in onChange event isn't updated

**Comment by AlexKart86** [comment]
This bug is reproduced on demo
http://react-component.github.io/tree-select/examples/dynamic.html
Select one value and after that try to select another value

at triggerChange method 
valueList array at this case includes 2 items  - old and new node. OnChange event receive the first value from array - old node  


The problem only appeared in the version 2.2.5, in 2.2.4 all is ok
